![](http://www.tshs.tp.edu.tw/images/bg/logo.jpg) 

## 多元選修課程：Python與人工智慧程式設計

# 【第七週】Python容器(Container)型別

Python提供數種不同的容器型別，來儲存不同類型的資料。各種不同的容器有其相似與不同之處，在操作和使用上也是。在先前的內容我們介紹過串列(List)，接下來要認識常用與重要的元組(Tuple)與字典(Dict)。

list
tuple
dictionary
set
queue
collection
array

### 【任務7-1】如何建立元組(Tuple)

元組(Tuple)在使用上和串列類似，在語法上有一點小小的不同，元組是用小括號 `( )` 來包含元素。下面的例子是建立一個包含3個元素的元組，元素之間用逗號接續。

In [1]:
t = (1, 2, 3, 4, 5)
t

(1, 2, 3, 4, 5)

呼叫 `type()` 函式可以看到 t 的型別為元組。

In [2]:
type(t)

tuple

[複習] 用 `len()` 函式查看元組中有3個元素。

In [3]:
len(t)

5

元組跟串列一樣是可迭代的，若要取出元組中的每一個元素，其中一個方式是用 for 迴圈。

In [4]:
for i in t:
    print(i)

1
2
3
4
5


### 【複習】你跟元組(Tuple)的第一次接觸

回憶一下，在9/25課程的"【挑戰】傳入不定數量的參數來呼叫函式"中，我們曾經嘗試設計一個函式來接收不定數量的參數來處理及計算各年份的汙染物顆數。

> $\Large P＝1000t^{1.25} ＋14000$

> 利用這個公式來計算2000年、2010年、2020年時每立方公分汙染物的顆數各為多少？

> 需求：
> - 呼叫函式傳多個年份參數，將所有年份的汙染物顆數加入到List中。
> - List做為函式的回傳值，並印出回傳結果。

下面的程式碼是參考解答，可以看到這邊允許多個引數的變數 `year` 即為 Tuple 型別。Tuple跟串列一樣(List)，都是可迭代的，所以可以用範例中 for 迴圈的示範，把元組中的元素一一拿出來。

In [5]:
def cal_pollutants(*year):
    P = []
    
    '''
    year 的型別為元組(tuple)，在後面的單元會介紹
    但在這邊的應用跟List的方面相當類似
    也可以用在for迴圈
    '''
    for i in year:
        t = i - 1980
        P.append(1000 * (t ** 1.25) + 14000)
    
    return P

# 印出List
print("印出List")
print(cal_pollutants(2000, 2010, 2020), "\n")

# 也可以再把回傳List的資料值逐筆印出
P = cal_pollutants(1980, 2000, 2010, 2020)   # 傳4個參數進去也可以

print("逐筆印出")

for i in P:
    print(i)

印出List
[56294.850537622566, 84210.41957962148, 114594.67437463484] 

逐筆印出
14000.0
56294.850537622566
84210.41957962148
114594.67437463484


### 【任務7-2】學會元組的索引及切片(slicing)

跟串列一樣，要取得元組中的元素，可以透過索引與切片。使用索引與切片時，記得要用中刮號 `[ ]`。

In [6]:
# 取得索引值1的元素 (第2個元素) 
t[1]

2

元組的切片(slicing)是取得串列部分內容。可以透過給定特定範圍的索引取得。

切片語法：
```python
元組名稱[起始值start:結束值stop:跨步值step]
```

想一想，下面元組切片的範例是不是似曾相識？對的，切片的用法跟串列的切片用法完全相同。

In [7]:
print(t[0:3])   # 索引值可以給範圍，範圍包含起始值但不包含結束值
print(t[3:])    # 範圍可以指定某一個元素之後的所有元素
print(t[:3])    # 範圍可以指定某一個元素之前的所有元素
print(t[-3:])   # 取得後n個元素
print(t[:-3])   # 不包含後n個元素
print(t[0:5:2]) # 每隔一個索引的元素

(1, 2, 3)
(4, 5)
(1, 2, 3)
(3, 4, 5)
(1, 2)
(1, 3, 5)


重要！！！元組是**不可變的(immutable)**，所以無法透過索引去改變元組中元素的值。如果嘗試這樣做時，執行時會產生錯誤。

In [8]:
t[2] = 99

TypeError: 'tuple' object does not support item assignment

### 【任務7-3】對元組進行 `+` 跟 `*` 會發生什麼事

回想字串的 `+` 跟 `*`，對元組進行相同的操作也會得到相同的效果。

In [9]:
t1 = (6, 7, 8, 9, 10)

兩個元組進行 `+`，可以視為把兩個元組合併。先前提到元組是不可變的，但透過這個方式，我們可以做到可以把新的元素加到元組中。

In [10]:
t = t + t1
t

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

把元組乘以2，也就是把元組元素重覆2次。

In [11]:
t3 = t * 2
t3

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

特別要留意的是，如果要將單一元素加到另一個元組中，除了用小括號將該元素包起來之外，還要在元素後加一個逗號，這樣子Python就可以正確認得是要做元組的 `+`。

In [12]:
t += (11,)
t

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)

### 【挑戰】休士頓火箭隊的死亡五小陣容，是不是真的很矮？

NBA休士頓火箭隊在比賽中喜歡擺出先發死亡五小陣容來跟對手比快速輪轉及三分球。死亡五小的身高分別為：6呎3吋，6呎5吋，6呎6吋，6呎7吋，6呎5吋。

挑戰內容：
- 請用Python程式寫一個英呎(feet)/英吋(inches)轉換為公分的函式

$$1feet=12inches$$

$$1inches=2.54cm$$

- 將轉換為公分的身高，存到一個元組(Tuple)裡面(提示：元組是不可變的)
- 計算元組中身高的平均值(提示：使用之前學過的 `sum()` 及 `len()` 函式，可以計算出總和與元素數目)

問題：
1. 請問死亡五小陣容的平均身高為幾公分？
2. 依照NBA官網提供的數字，在2019-2020球季NBA球員的平均身高約為199.5公分。那死亡五小的身高跟全NBA球員的平均身高相比，是較高還是較矮？

In [13]:
# 請在下一行開始輸入你的程式碼


### 【任務7-4】認識字典(dict)

字典中，每一個元素都由鍵(key)和值(value)組成，鍵與值中間用冒號分隔，元素則用大刮號 `{ }` 包起來。字典中的鍵(key)不能重複。

語法如下：

```python
d={key1:value1, key2:value2}
```

也可以用下列的方式建立字典：

```python
d = dict(key1=value1, key2=value2)
```

In [14]:
groceries = {'milk':960, 'apple':3, 'bread':10}

要取得字典中單一元素的值，可以使用下列語法：

```python
字典名稱['鍵名稱']
```

In [15]:
groceries['apple']

3

字典很適合拿來做為儲存資料的方式，下面我們看到存放電影資訊的字典，可以看到在演員的值(value)用串列來存放多個演員的名字。

In [16]:
movie = {'name':'TENENT天能',                #電影名稱
         'year':2020,                 #電影上映年份
         'director':'克里斯多福·諾蘭',  #導演
         'writer':'克里斯多福·諾蘭',    #編劇
         'actors':['約翰·大衛·華盛頓', '羅伯·派汀森', '伊莉莎白·戴比基'],  #演員
        }

movie

{'name': 'TENENT天能',
 'year': 2020,
 'director': '克里斯多福·諾蘭',
 'writer': '克里斯多福·諾蘭',
 'actors': ['約翰·大衛·華盛頓', '羅伯·派汀森', '伊莉莎白·戴比基']}

### 【任務7-5】如何從字典中新增或刪除元素

新增元素時，新增一組鍵/值的組合即可，語法如下：

```python
字典名稱['新的鍵']=值
```

In [17]:
groceries['juice']=1000

在字典內多了 juice 元素。

In [18]:
groceries

{'milk': 960, 'apple': 3, 'bread': 10, 'juice': 1000}

欲刪除元素時，透過呼叫 `pop()` 函式，傳入要刪除元素的鍵。

In [19]:
groceries.pop('apple')

3

已將 apple 元素從字典中刪除。

In [20]:
groceries

{'milk': 960, 'bread': 10, 'juice': 1000}

### 【試一試】如果字典的鍵(key)重複會發生什麼事

1. Python會跳出錯誤
2. 會有兩個鍵相同的元素
3. 什麼事都不會發生
4. 後面的值會取代前一個值

In [21]:
# 請寫下你的答案


### 【任務7-6】想要取出字典中的鍵(key)與值(value)該怎麼做

字典是可迭代的，但由於字典元素包含了鍵與值，所以要迭代取出所有鍵與值的方式略有不同。先使用 `items()` 函式取後字典的視圖(view)，再逐筆印出各個鍵與值。

In [22]:
for keys, values in groceries.items():
    print(keys, values)

milk 960
bread 10
juice 1000


若想要知道字典中所有的鍵或所有的值，可以透過 `keys()` 與 `values()` 函式。

In [23]:
groceries.keys()

dict_keys(['milk', 'bread', 'juice'])

In [24]:
groceries.values()

dict_values([960, 10, 1000])

### 【挑戰】用字典來儲存與計算死亡五小的平均身高

NBA休士頓火箭隊在比賽中喜歡擺出先發死亡五小陣容來跟對手比快速輪轉及三分球。死亡五小的身高分別為：190.5, 195.58, 198.12, 200.66, 195.58公分。

挑戰內容：
- 死亡五小的名字與身高已經用一個字典儲存，請先取出字典中的值(提示：`values()`)。
- 用 for 迴圈迭代一一取出字典中的值，即為身高。
- 計算身高的平均值(提示：使用之前學過的 `sum()` 及 `len()` 函式，可以計算出總和與元素數目)。

問題：請用Python程式計算死亡五小陣容的平均身高

In [25]:
# 建立一個有4組key-value的字典
# 在這裡key是球員名稱，value是身高
Hampton5 = {'龜龜':190.5, '大鬍子':195.58, '塔克':195.58, 'Covington':200.66}
# 加入第5個球員
Hampton5['豪斯']=198.12

print(Hampton5)

{'龜龜': 190.5, '大鬍子': 195.58, '塔克': 195.58, 'Covington': 200.66, '豪斯': 198.12}


In [26]:
# 請在下一行開始輸入你的程式碼


### 【複習】我們已經學過3種常用的容器型別，還記得嗎？

Python各種容器型別有其相似與不同之處，在操作和使用上也是，下表列出已經學過的串列、元組、字典等容器，同學們可以比較與複習。

|容器型別|語法範例|括號|迭代|是否可變(mutable)|
|---|---|---|---|---|
|串列(List)|a=[1, 2, 3]|中括號|可迭代|可變|
|元組(Tuple)|a=(1, 2, 3)|小括號|可迭代|不可變(immutable)|
|字典(Dict)|a={key1:value1, key2:value2}|大括號|可迭代|可變|

Python跟很多程式語言一樣，均有內建的陣列(Array)型別。不過在Python社群和AI程式設計領域中，更強大與更受歡迎的是 NumPy 陣列，接下來我們來初步認識 NumPy 套件。

<img width=150 src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/200px-NumPy_logo.svg.png"></img>

### 【任務7-7】初探NumPy陣列

NumPy 是廣受歡迎的 open source Python 程式庫，支援多維度陣列與矩陣運算，也針對陣列運算提供大量的數學函式庫。

NumPy 的核心是由 C 語言開發，所以在陣列與矩陣運算時具有高效能的特性。

2019 年時 GitHub 統計指出有 74% 的機器學習專案中使用 NumPy。

In [27]:
# Colab 已經預先安裝 NumPy，所以只要輸入 import 就可以使用。
import numpy as np

使用 `array()` 函式，可將串列或元組 (tuple) 的值建立為 NumPy array。

In [28]:
# 使用 list
a = np.array([1, 2, 3, 4, 5])
# 使用元組
b = np.array((6, 7, 8))

In [29]:
print(a)
print(b)

[1 2 3 4 5]
[6 7 8]


要建立多維陣列，簡單的理解方式就是陣列中的元素也是陣列，呼叫 `array()` 函式時，只要將 list 中的元素也是 list 傳入即可。下面的例子是建立二維陣列。

In [30]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


使用 `shape` 屬性，可以查看多維陣列的形狀。如下例 a 陣列是一個 2 $\times$ 3 的二維陣列。

In [31]:
a.shape

(2, 3)

若要建立二維陣列，也可以用 `reshape()` 函式，將一維陣列轉換為二維陣列。但這邊要注意的是，`reshape()` 引數中的維度乘積要等於要轉換前的元素數目。例如，有6個元素的一維陣列，可以重塑為 2 $\times$ 3 或是 3 $\times$ 2 的二維陣列。

In [32]:
a = np.array([1, 2, 3, 4, 5, 6])
len(a)   # 用 len() 函式算出元素數目

6

In [33]:
a.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

### 【任務7-8】NumPy陣列的四則運算

陣列的加減乘除四則運算，可以使用運算子 (+, -, *, /) 或是呼叫函式來進行，語法及對照如下表：

|運算子|函式||
|---|---|---|
|a + b |np.add(a, b)|加法|
|a - b |np.substract(a, b)|減法|
|a * b |np.multiply(a, b)|乘法|
|a / b |np.divide(a, b)|除法|
|a % b |np.mod(a, b)|求餘數|

以上運算子的部分，使用與 Python 相同的運算子。

運算的時候，陣列的形狀 (shape) 必須相同。

下面的範例是兩個陣列形狀完全相同的情況下，進行相加。

In [34]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 4, 5])
a + b

array([ 2,  4,  6,  8, 10])

In [35]:
np.add(a, b)

array([ 2,  4,  6,  8, 10])

### 【任務7-9】NumPy陣列廣播(Broadcasting)

廣播是非常方便的機制，在做運算時只要符合廣播規則，NumPy陣列就會自動執行element-wise的計算。

簡單來說，如果可以將較小的陣列形狀，擴大到較大陣列的形狀相同，就可以進行廣播。

廣播的規則如下：
1. 陣列與純量進行運算
2. 其中一個維度為1的話

如果符合上面規則，而且較小的陣列可以擴大到與較大陣列的形狀相同的話，就可以成功完成廣播；否則會產生錯誤。

例如：陣列 [1, 2, 3] 與整數2相乘時，會先將整數2擴大為 [2, 2, 2] 讓形狀相同，再進行相乘。

In [36]:
a = np.array([1, 2, 3])
b = 2
a*b

array([2, 4, 6])

下面用三維陣列來做說明上述第2個規則。

`arange()` 函式是用來產生等差數列的陣列。`np.arange(6)` 會產生 [0, 1, 2, 3, 4, 5] 的陣列。

In [37]:
a = np.arange(12).reshape(2, 2, 3)
b = np.arange(6).reshape(2, 1, 3)

In [38]:
a + b

array([[[ 0,  2,  4],
        [ 3,  5,  7]],

       [[ 9, 11, 13],
        [12, 14, 16]]])

### 【任務7-10】軸與維度

軸 (axis) 在 NumPy 多維陣列中是很重要觀念，但是在應用上容易混淆。軸的數目也就是 NumPy 陣列的維度 (dimension) 數，軸的順序編號從 0 開始，下面例子用圖示來解說。

對一維陣列來說，只有一個軸，所以 axis 為 0。

In [39]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

以圖示來說明一維陣列的軸。

![](ds7-1d_axis.png)

二維陣列會有 2 個軸。二維陣列的軸 0 就是沿著 row 的軸，而軸 1 是沿著 column 的軸。

In [40]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

以圖示來說明二維陣列的軸。

![](ds7-2D_axis.png)

### 【任務7-11】點積(Dot Product)

點積是AI程式設計中常會用到的運算，點積運算時須遵循的規則說明如下：

進行點積運算須注意形狀必須注意形狀 (shape)。若是兩個向量的點積，兩個向量的元素數目也須相同，或其中一個數目為 1 (廣播)。

若是兩個多維陣列 (矩陣) 的點積，則中間兩個大小要相同才能進行點積，例如：

$(2, 3) \cdot (3, 4) \to $ 成為 $(2, 4)$

點積的運算如下，假設 A 和 B：

$ A = 
\begin{bmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}
\end{bmatrix}
$

$ B =
\begin{bmatrix}
b_{11} & b_{12} & b_{13} & b_{14}\\
b_{21} & b_{22} & b_{23} & b_{24}\\
b_{31} & b_{32} & b_{33} & b_{34}
\end{bmatrix}
$

兩個矩陣進行點積

![](ds7-dot_product.png)

In [41]:
A = np.arange(6).reshape(2, 3)
B = np.arange(12).reshape(3, 4)

In [42]:
print(A)
print(B)

[[0 1 2]
 [3 4 5]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [43]:
np.dot(A, B)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

### 【挑戰】用NumPy陣列來儲存與計算死亡五小的平均身高

死亡五小的身高分別為：190.5, 195.58, 198.12, 200.66, 195.58公分。

挑戰內容：
- 建立一個NumPy陣列，其中的元素值為死亡五小的身高。
- 呼叫 NumPy 提供的計算平均數函式，計算死亡五小的平均身高。

平均數函式基本語法如下：

```python
np.average(NumPy陣列名稱)
```

In [44]:
# 請在下一行開始輸入你的程式碼
